### ISSUE TITLE
class bug?

### ISSUE THREAD

**Issue by friosavila** [benjann/palettes#1]
Hi
I was wondering if what I found is just a bug, or something withing colorpalette
Basically, I'm playing with some new palettes, and wanted to recycle them.

Lets say that I created a program that defines the red_blue palette, without  "c_local class"

If I want to interpolate and create 4 different colors I could use this:
`colorpalette red_blue, n(4)` 
However, what if I want to recycle the color (Red blue red blue etc)
The helpfile suggests I could do this:
`colorpalette red_blue, n(4)  class(q)`
But it doesn't seem to work. In fact, it creates no error if I do:
`colorpalette red_blue, n(4)  class(asdasd)`
Thank you
Fernando

**Comment by benjann** [comment]
Hi, thank for reporting this. Option `class()` had no effect if used with a _colorlist_ or with a custom palette provided by a program  I now posted an update that should fix this.

> But it doesn't seem to work. In fact, it creates no error if I do:
colorpalette red_blue, n(4) class(asdasd)

This is intentional. The classes "recognized" by `colorpalette` are `qualitative`, `sequential`, and `diverging`, but you can also set the class to anything else (the specified string will be returned in `r(pclass)`). 

ben
